### ISSUE TITLE
'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by clorieanne** [nathancahill/flask-inputs#18] opened 2018-07-02 08:18 UTC
Hello, 
Thanks for "flask-inputs" library. It is working on my python2 but on python3, it gives an error `'dict'`` object has no attribute 'iteritems'''`

I also search that `iteritems` is no longer supported in python3, is there other way to use `flask-inputs` on python3? Or if none, what other ways I can use to validate the json input for my [POST] method request. 

Thank you!

**Comment by aodj** [comment] 2018-07-31 14:56
It might be that the repo is abandoned. The last commit was over a year ago so it might just be easier to fork it and make the changes yourself.

**Comment by nathancahill** [comment] 2018-07-31 19:58
Duplicate of #9, now resolved.

**Closed by nathancahill** 2018-07-31 19:58 UTC
